'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const esbuild = require('esbuild');
const WORK = path.resolve(__dirname, '../..');
const antdFixture = `import React from 'react';
export const App={useApp:()=>window.__autonomyUiServices};
export const theme={useToken:()=>({token:{colorBorderSecondary:'#bbb',borderRadiusLG:8,colorBgContainer:'#fff'}})};
export const Button=({children,onClick,disabled,loading})=><button onClick={onClick} disabled={disabled||loading}>{children}</button>;
export const Flex=({children,...props})=><div data-testid={props['data-testid']}>{children}</div>;
export const Typography={Text:({children,strong})=><span data-strong={strong}>{children}</span>,Title:({children})=><h4>{children}</h4>,Paragraph:({children})=><p>{children}</p>};
export const Drawer=({children,title,open,onClose})=>open?<section data-drawer={title}><h3>{title}</h3><button onClick={onClose}>{title}.close</button>{children}</section>:null;
export const Alert=({title,description})=><aside>{title}{description}</aside>;
export const Empty=({description})=><p>{description}</p>;export const Spin=()=>null;export const Tag=({children})=><span>{children}</span>;
export const Checkbox=({children,checked,disabled,onChange})=><label><input type='checkbox' checked={checked} disabled={disabled} onChange={onChange}/>{children}</label>;
Checkbox.Group=({value,options,onChange,disabled})=><div>{options.map(item=><label key={item.value}><input type='checkbox' value={item.value} checked={value.includes(item.value)} disabled={disabled} onChange={e=>onChange(e.target.checked?[...value,item.value]:value.filter(v=>v!==item.value))}/>{item.label}</label>)}</div>;
export const Select=({value,onChange,options,mode,disabled,...props})=><select aria-label={props['aria-label']||props.placeholder} multiple={mode==='multiple'} disabled={disabled} value={value||(mode==='multiple'?[]:'')} onChange={e=>onChange(mode==='multiple'?[...e.target.selectedOptions].map(o=>o.value):(e.target.value||undefined))}>{mode!=='multiple'&&<option value=''></option>}{options.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select>;
export const Input=({value,onChange,...props})=><input aria-label={props['aria-label']} value={value} onChange={onChange}/>;
Input.TextArea=({value,onChange,disabled,readOnly,...props})=><textarea aria-label={props['aria-label']} disabled={disabled} readOnly={readOnly} value={value} onChange={onChange}/>;
export const InputNumber=({value,onChange,disabled})=><input type='number' disabled={disabled} value={value} onChange={e=>onChange(Number(e.target.value))}/>;
export const Tabs=({items,activeKey,onChange})=><div className='test-tabs'>{items.map(item=><button key={item.key} onClick={()=>onChange(item.key)}>{item.label}</button>)}{items.find(item=>item.key===activeKey)?.children}</div>;
export const Descriptions=({items})=><dl>{items.map(item=><div key={item.key}>{item.label}{item.children}</div>)}</dl>;
export const Modal=({title,open,children,footer,onOk,onCancel,okText,confirmLoading})=>open?<section data-modal={title}><h3>{title}</h3>{children}{footer!==null&&<button disabled={confirmLoading} onClick={onOk}>{okText}</button>}<button onClick={onCancel}>{title}.cancel</button></section>:null;`;
test('real React autonomy drawer preserves scope, consent, conflict, expiry and A/B readiness across actual controls', async t => {
  const allowed = path.join(WORK, 'isolated-runs'); fs.mkdirSync(allowed, { recursive: true });
  const root = fs.mkdtempSync(path.join(allowed, 'm2-autonomy-ui-')); t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  await esbuild.build({ entryPoints: [path.join(__dirname, 'drawer-browser-entry.tsx')], bundle: true, platform: 'browser', format: 'iife', outfile: path.join(root, 'fixture.js'), define: { 'process.env.NODE_ENV': '"production"' }, plugins: [{ name: 'ui-fixture-controls', setup(build) {
    build.onResolve({ filter: /^antd$/ }, () => ({ path: 'antd-fixture', namespace: 'fixture' }));
    build.onResolve({ filter: /^@ant-design\/icons$/ }, () => ({ path: 'icons-fixture', namespace: 'fixture' }));
    build.onLoad({ filter: /.*/, namespace: 'fixture' }, args => ({ contents: args.path === 'antd-fixture' ? antdFixture : 'export const PlusOutlined=()=>null,ReloadOutlined=()=>null,SafetyCertificateOutlined=()=>null;', loader: 'tsx', resolveDir: WORK }));
  } }] });
  fs.writeFileSync(path.join(root, 'index.html'), '<!doctype html><html><body><script src="fixture.js"></script></body></html>');
  const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE; delete env.ELECTRON_DISABLE_SANDBOX;
  const result = spawnSync(process.execPath, [path.join(__dirname, 'autonomy-browser-main.cjs'), root], { cwd: WORK, env, encoding: 'utf8', timeout: 30000 });
  const reportFile = path.join(root, 'results.json'), report = fs.existsSync(reportFile) ? JSON.parse(fs.readFileSync(reportFile, 'utf8')) : { error: result.stderr || String(result.error) };
  assert.equal(result.status, 0, report.error); assert.equal(report.ok, true, report.error); assert.equal(report.results.length, 22);
  for (const scenario of report.results) t.diagnostic(scenario);
});
